sMainControlPrefix  = 'Main'
sControl            = '_Ctrl'
sControlGroup       = '_CtrlGrp'
sRigGroup           = 'RigGrp'
sJointsGroup        = 'JointsGrp'
sModelGroup         = 'ModelGrp'
sBuilderGroup       = 'BuilderGrp'
sRigCompsGroup      = 'RigComponentsGrp'
sRigPartsGroup      = 'RigPartsGrp'
sRigPartsFixedGroup = 'RigPartsFixedGrp'
sIKPrefix           = 'IK_'
sFKPrefix           = 'FK_'
sExpressionPrefix   = 'Expr_'
sSlavePrefix        = 'Slave_'
sControlsGroup      = 'ControlsGrp'
sTwistJointsGroup   = 'TwistJointsGrp'
sTwistBegin         = 'TwistBegin'
sTwistEnd           = 'TwistEnd'
sTwistKnob          = 'TwistKnob'
sTwistIKHandle      = 'Twist_ikHandle'
sProxy              = 'Proxy'
sCurve              = 'Curve'
sSplineIKHandle     = 'Spline_ikHandle'
sIKHandle           = 'ikHandle'
sPoleVector         = 'PV'
sSync               = 'Sync'
sDeformationGroup   = 'DeformationGrp'

s_JointsGroup        = '_' + sJointsGroup
s_ModelGroup         = '_' + sModelGroup
s_BuilderGroup       = '_' + sBuilderGroup
s_RigGroup           = '_' + sRigGroup
s_RigCompsGroup      = '_' + sRigCompsGroup
s_RigPartsGroup      = '_' + sRigPartsGroup
s_RigPartsFixedGroup = '_' + sRigPartsFixedGroup
s_IKPrefix           = '_' + sIKPrefix
s_FKPrefix           = '_' + sFKPrefix
s_ExpressionPrefix   = '_' + sExpressionPrefix
s_ControlsGroup      = '_' + sControlsGroup
s_TwistJointsGroup   = '_' + sTwistJointsGroup
s_TwistBegin         = '_' + sTwistBegin
s_TwistEnd           = '_' + sTwistEnd
s_TwistKnob          = '_' + sTwistKnob
s_TwistIKHandle      = '_' + sTwistIKHandle
s_Proxy              = '_' + sProxy
s_Curve              = '_' + sCurve
s_SplineIKHandle     = '_' + sSplineIKHandle
s_IKHandle           = '_' + sIKHandle
s_PoleVector         = '_' + sPoleVector
s_Sync               = '_' + sSync

sFootExtJnt         = 'footExtJnt'
sFootIntJnt         = 'footIntJnt'
sFootBaseJnt        = 'footBaseJnt'
sFootBaseSwiveJnt   = 'footBaseSwiveJnt'
sFootToeSwiveJnt    = 'footToeSwiveJnt'
sFootToeProxy       = 'footToeProxy'
sFootBallProxy      = 'footBallProxy'
sFootAnkleProxy     = 'footAnkleProxy'
sToeProxyPVlocator  = 'toeProxyPVlocator'
sBallProxyPVlocator = 'ballProxyPVlocator'

sLeftLegIKFKSwitch  = 'leftLegIKFKSwitch'
sRightLegIKFKSwitch = 'rightLegIKFKSwitch'
sLeftArmIKFKSwitch  = 'leftArmIKFKSwitch'
sRightArmIKFKSwitch = 'rightArmIKFKSwitch'

sLeftLegFKLocalToWorldSwitch  = 'leftLegFKLocalToWorldSwitch'
sRightLegFKLocalToWorldSwitch = 'rightLegFKLocalToWorldSwitch'
sLeftArmFKLocalToWorldSwitch  = 'leftArmFKLocalToWorldSwitch'
sRightArmFKLocalToWorldSwitch = 'rightArmFKLocalToWorldSwitch'

sLeftLegIKFKAutoHide  = 'leftLegIKFKAutoHide'
sRightLegIKFKAutoHide = 'rightLegIKFKAutoHide'
sLeftArmIKFKAutoHide  = 'leftArmIKFKAutoHide'
sRightArmIKFKAutoHide = 'rightArmIKFKAutoHide'

sPrefixAttr              = 'Prefix'
sFKSyncTargets           = 'FKSyncTargets'
sFKSyncTarget            = 'FKSyncTarget'
sFKSyncSources           = 'FKSyncSources'
sFKSyncSource            = 'FKSyncSource'
sIKMainControl           = 'IKMainControl'
sIKMainRotationControl   = 'IKMainRotationControl'
sPVControl               = 'PVControl'
sIKMainControlSyncTarget = 'IKMainControlSyncTarget'
sPVLocatorSyncTarget     = 'PVLocatorSyncTarget'