sControl            = '_Ctrl'
sControlGroup       = '_CtrlGrp'
sRigGroup           = 'RigGrp'
sJointsGroup        = 'JointsGrp'
sModelGroup         = 'ModelGrp'
sRigCompsGroup      = 'RigComponentsGrp'
sRigPartsGroup      = 'RigPartsGrp'
sRigPartsFixedGroup = 'RigPartsFixedGrp'
sIKPrefix           = 'IK_'
sFKPrefix           = 'FK_'
sControlsGroup      = 'ControlsGrp'
sTwistJointsGroup   = 'TwistJointsGrp'
sTwistBegin         = 'TwistBegin'
sTwistEnd           = 'TwistEnd'
sTwistKnob          = 'TwistKnob'
sTwistIKHandle      = 'Twist_ikHandle'
sProxy              = 'Proxy'

s_JointsGroup        = '_' + sJointsGroup
s_ModelGroup         = '_' + sModelGroup
s_RigGroup           = '_' + sRigGroup
s_RigCompsGroup      = '_' + sRigCompsGroup
s_RigPartsGroup      = '_' + sRigPartsGroup
s_RigPartsFixedGroup = '_' + sRigPartsFixedGroup
s_ControlsGroup      = '_' + sControlsGroup
s_TwistJointsGroup   = '_' + sTwistJointsGroup
s_TwistBegin         = '_' + sTwistBegin
s_TwistEnd           = '_' + sTwistEnd
s_TwistKnob          = '_' + sTwistKnob
s_TwistIKHandle      = '_' + sTwistIKHandle
s_Proxy              = '_' + sProxy