def SE_RigEnum(**namedValues):
    return type('SERigEnum', (), namedValues)

eRigSide = SE_RigEnum(
    RS_Unknown = 0,
    RS_Left    = 1,
    RS_Right   = 2,
    RS_Center  = 3,
    RS_Max     = 4
    )

eRigSideStringTable = [
    'RS_Unknown',    
    'RS_Left',
    'RS_Right',
    'RS_Center'
    ]

eRigType = SE_RigEnum(
    RT_Unknown              = 0,
    RT_ShoulderFK           = 1,
    RT_ElbowFK              = 2,
    RT_WristFK              = 3,
    RT_SpineUpperBody       = 4,
    RT_SpineChest           = 5,
    RT_SpineChestLocal      = 6,
    RT_SpinePelvis          = 7,
    RT_SpinePelvisLocal     = 8,
    RT_SpineFK              = 9,
    RT_Hip                  = 10,
    RT_Knee                 = 11,
    RT_AnkleIKRotation      = 12,
    RT_FootIKMain           = 13,
    RT_FootBaseSwive        = 14, 
    RT_FootToeSwive         = 15,
    RT_FootRotation         = 16,
    RT_LegFK                = 17,
    RT_Clavicle             = 18,
    RT_Hand                 = 19,
    RT_ThumbFK              = 20,
    RT_IndexFK              = 21,
    RT_MiddleFK             = 22,
    RT_RingFK               = 23,
    RT_PinkyFK              = 24,
    RT_LegPV                = 25,
    RT_ArmPV                = 26,
    RT_ArmIKMain            = 27,
    RT_NeckFK               = 28,
    RT_HeadFK               = 29,
    RT_HeadAimIK            = 30,
    RT_OnFaceIK             = 31,
    RT_OnFaceFK             = 32,
    RT_Global               = 33,
    RT_Component            = 34,
    RT_LegComponent         = 35,
    RT_ArmComponent         = 36,
    RT_SpineComponent       = 37,
    RT_NeckComponent        = 38,
    RT_HandComponent        = 39,
    RT_FacialComponent      = 40,
    RT_Max                  = 41
    )

eRigTypeStringTable = [
    'RT_Unknown',
    'RT_ShoulderFK',
    'RT_ElbowFK',
    'RT_WristFK',
    'RT_SpineUpperBody',
    'RT_SpineChest',
    'RT_SpineChestLocal',
    'RT_SpinePelvis',
    'RT_SpinePelvisLocal',
    'RT_SpineFK',
    'RT_Hip',
    'RT_Knee',
    'RT_AnkleIKRotation',
    'RT_FootIKMain',
    'RT_FootBaseSwive',
    'RT_FootToeSwive',
    'RT_FootRotation',
    'RT_LegFK',
    'RT_Clavicle',
    'RT_Hand',
    'RT_ThumbFK',
    'RT_IndexFK',
    'RT_MiddleFK',
    'RT_RingFK',
    'RT_PinkyFK',
    'RT_LegPV',
    'RT_ArmPV',
    'RT_ArmIKMain',
    'RT_NeckFK',
    'RT_HeadFK',
    'RT_HeadAimIK',
    'RT_OnFaceIK',
    'RT_OnFaceFK',
    'RT_Global',
    'RT_Component',
    'RT_LegComponent',
    'RT_ArmComponent',
    'RT_SpineComponent',
    'RT_NeckComponent',
    'RT_HandComponent',
    'RT_FacialComponent'
    ]

eRigColor = SE_RigEnum(
    RC_Red    = 13,
    RC_Blue   = 6,
    RC_Yellow = 22
    )

eRigFacing = SE_RigEnum(
    RF_X = 1,
    RF_Y = 2,
    RF_Z = 3
    )

eRigFacialControlID = SE_RigEnum(
    RFCID_JawPos         = 0,
    RFCID_JawMidPos      = 1,
    RFCID_JawIK          = 2,
    RFCID_LipCloseFK     = 3,
    RFCID_EyesAimIK      = 4,
    RFCID_LeftEyeAimIK   = 5,
    RFCID_RightEyeAimIK  = 6
    )

eRigFacialActionUnitType = SE_RigEnum(
    AU_01_L             = 0,
    AU_01_R             = 1,
    AU_02_L             = 2,
    AU_02_R             = 3,
    AU_04_L             = 4,
    AU_04_R             = 5,
    AU_05_L             = 6,
    AU_05_R             = 7,
    AU_06_L             = 8,
    AU_06_R             = 9,
    AU_07_L             = 10,
    AU_07_R             = 11,
    AU_09_L             = 12,
    AU_09_R             = 13,
    AU_10_L             = 14,
    AU_10_R             = 15,
    AU_11_L             = 16,
    AU_11_R             = 17,
    AU_12_L             = 18,
    AU_12_R             = 19,
    AU_12_OL            = 20,
    AU_12_OR            = 21,
    AU_12_Blink_L       = 22,
    AU_12_Blink_R       = 23,
    AU_13_L             = 24,
    AU_13_R             = 25,
    AU_14_L             = 26,
    AU_14_R             = 27,
    AU_15_L             = 28,
    AU_15_R             = 29,
    AU_16_L             = 30,
    AU_16_R             = 31,
    AU_17_D             = 32,
    AU_17_U             = 33,
    AU_18_L             = 34,
    AU_18_R             = 35,
    AU_20_L             = 36,
    AU_20_R             = 37,
    AU_20_NL            = 38,
    AU_20_NR            = 39,
    AU_22_D             = 40,
    AU_22_U             = 41,
    AU_23_D             = 42,
    AU_23_U             = 43,
    AU_24               = 44,
    AU_25_D             = 45,
    AU_25_U             = 46,
    AU_26_Fix           = 47,
    AU_26_CloseFix      = 48,
    AU_28_D             = 49,
    AU_28_U             = 50,
    AU_Puff_L           = 51,
    AU_Puff_R           = 52,
    AU_Shrink_L         = 53,
    AU_Shrink_R         = 54,
    AU_Blink_L          = 55,
    AU_Blink_R          = 56,
    AU_Throat           = 57,
    AU_JawForward       = 58,
    AU_LipClose         = 59,
    AU_LowLipCompress   = 60,
    AU_UpLipCompress    = 61,
    AU_Eye_L_LookLeft   = 62,
    AU_Eye_L_LookRight  = 63,
    AU_Eye_L_LookUp     = 64,
    AU_Eye_L_LookDown   = 65,
    AU_Eye_R_LookLeft   = 66,
    AU_Eye_R_LookRight  = 67,
    AU_Eye_R_LookUp     = 68,
    AU_Eye_R_LookDown   = 69,
    AU_10_OL            = 70,
    AU_10_OR            = 71
    )

eRigFacialControlType = SE_RigEnum(
    RFCT_InnerBrow       = 0,
    RFCT_OuterBrow       = 1,
    RFCT_UpperLid        = 2,
    RFCT_LowerLid        = 3,
    RFCT_OuterEyeCorner  = 4,
    RFCT_Nosewing        = 5,
    RFCT_Muzzle          = 6,
    RFCT_UpperLip        = 7,
    RFCT_LowerLip        = 8,
    RFCT_Mouth           = 9,
    RFCT_MouthCorner     = 10,
    RFCT_Jaw             = 11,
    RFCT_Cheek           = 12,
    RFCT_Chin            = 13
    )



